<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <NoWarn>CS1591</NoWarn>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="2.3.0" />
    <PackageReference Include="Vortice.DXGI" Version="2.3.0" />
    <PackageReference Include="Vortice.D3DCompiler" Version="2.3.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
  </ItemGroup>

</Project>
